### ISSUE TITLE
work timeline mouseover bug

### ISSUE THREAD

**Issue by kkoskelin** [christophersbarrett/thegoldentoilet.github.io#1]
move mouse vertically along right edge of work period (where balloon) slightly overlaps" and I think that mouseover/mouseout is continually triggered, causing balloon to show, then hide, show, hide.  produces a flickering effect.

![](http://img1.wikia.nocookie.net/__cb20130803083139/disney/images/5/5c/Mr-t.jpg)

**Comment by christophersbarrett** [comment]
You are a nitpicker.

**Comment by ericsorenson** [comment]
doesn't work. please fix.

**Comment by christophersbarrett** [comment]
What version of IE are you running @dubharmonic?

**Comment by ericsorenson** [comment]
@thegoldentoilet the one with the blue e

**Comment by kkoskelin** [comment]
![](http://24.media.tumblr.com/tumblr_l5842dqeqB1qbylvso1_400.png)

**Comment by ericsorenson** [comment]
Problem?

**Comment by christophersbarrett** [comment]
closing issue. will not fix.
